name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  liquibase_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build images & run tests
      run: |
        docker image build -f Liquibase.Dockerfile .
        docker-compose up
