name: Docker Image CI

on:
  pull_request:
    branches: [ master ]

jobs:
  liquibase_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Liquibase image
      run: docker image build -f Liquibase.Dockerfile .
    - name: Run the tests
      run: docker-compose up
